[package]
name = "ddlog-utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
triomphe = "0.1.3"

    [dependencies.xxhash-rust]
    version = "0.8.2"
    features = ["xxh3", "const_xxh3"]
