[package]
name = "stable-hash"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
blake3 = "1.3.1"
qp-trie = "0.8.0"
arrayvec = "0.7.2"
bytemuck = "1.9.1"
ddlog-utils = { path = "../ddlog-utils" }
